
name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    env:
      MYTOKEN : "value1"
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg install -y libunwind icu libinotify openssl misc/compat13x dotnet
    
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          fetch https://repo.jellyfin.org/files/server/linux/latest-stable/amd64/jellyfin_10.9.6-amd64.tar.xz -o jellyfin.tar.gz
          tar xf jellyfin.tar.xz
          pushd jellyfin
          
