
name: Test

on: [push]

jobs:
  test:
    runs-on: ubicloud-standard-4
    # runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y git libunwind icu libinotify openssl misc/compat13x dotnet python311 npm-node20 rsync
        run: |
          echo $SHELL
          pwd
          ls -lah
          whoami
          freebsd-version
          git clone --depth=1 https://git.freebsd.org/ports.git /usr/ports
          cd ./building/ports/jellyfin
          export DEFAULT_VERSIONS=ssl=openssl
          touch ./iamhere
          make
    - name: Compress
      run: tar -czf ./upload.tar.gz ./building
    - name: Fix upload-artifact for self-hosted hunner
      run: |
        curl https://api.github.com/meta | jq .domains.actions
    - name: Export Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jellyfin-artifacts
        path: ./upload.tar.gz
        overwrite: true
        compression-level: 0 # We are already gzipping above, makes no sense to compress again. Remove wehen upload-artifact fixes its stuff
