
name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    env:
      MYTOKEN : "value1"
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg install -y git libunwind icu libinotify openssl misc/compat13x dotnet python311 npm-node20 rsync
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          git clone --depth=1 https://git.freebsd.org/ports.git /usr/ports
          rm -rf /usr/ports/multimedia/jellyfin
          rsync -a ./building/ports/jellyfin /usr/ports/multimedia/
          cd /usr/ports/multimedia/jellyfin
          make
          
